def grade() :
    print('+', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('+', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('+')
#linha2
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|')
#linha3
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|')
#linha4
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|')
#linha5
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|')
#linha6
    print('+', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('+', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('+')
#linha77
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|')
#linha8
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|')
#linha9
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|')
#linha10
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print(' ', end=' ')
    print('|')
#linha11
    print('+', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('+', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('+')

grade()
